# Generated by Django 3.0.14 on 2021-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
