# Generated by Django 3.0.14 on 2021-05-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210528_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='available',
        ),
    ]
