# Generated by Django 3.0.14 on 2021-05-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='body2',
        ),
    ]
