# Generated by Django 3.0.14 on 2021-05-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Discounted_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
