# Generated by Django 3.0.14 on 2021-06-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210629_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
    ]
