# Generated by Django 3.0.14 on 2021-06-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='body',
        ),
        migrations.RemoveField(
            model_name='main',
            name='created',
        ),
        migrations.RemoveField(
            model_name='main',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='main',
            name='updated',
        ),
    ]
